FILE (GLOB_RECURSE CMAKELISTS "CMakeLists.txt")
FILE (GLOB_RECURSE CMAKEMODULES "*.cmake")
LIST (APPEND CMAKEFORMATTINGFILES ${CMAKELISTS} ${CMAKEMODULES})
FIND_PROGRAM (CMAKEFORMAT cmake-format HINTS $ENV{HOME}/.local/bin)

INCLUDE (CMakeHelperFunctions)
REMOVEFILESUNDERFOLDER (${CMAKE_SOURCE_DIR}/${TOP_BUILD} CMAKEFORMATTINGFILES)

IF (NOT CMAKEFORMAT)
  MESSAGE (
    WARNING
      "cmake-format not found ${CMAKEFORMAT}. Not formatting CMakeLists and cmake modules!"
  )
ENDIF (NOT CMAKEFORMAT)

FOREACH (FILE ${CMAKEFORMATTINGFILES})
  EXECUTE_PROCESS (COMMAND cmake -E echo "Formatting: ${FILE}")
  EXECUTE_PROCESS (COMMAND ${CMAKEFORMAT} -i ${FILE} ${FILE})
ENDFOREACH (FILE)
