FILE (GLOB_RECURSE HPP ${CMAKE_SOURCE_DIR} "*.hpp")
FILE (GLOB_RECURSE CPP ${CMAKE_SOURCE_DIR} "*.cpp")
FILE (GLOB_RECURSE C_H ${CMAKE_SOURCE_DIR} "*.h")
LIST (APPEND CHECK_CXX_SOURCE_FILES ${HPP} ${CPP} ${C_H})
STRING (REGEX REPLACE "${CMAKE_SOURCE_DIR}/" "" BUILDDIRECTORY
                      ${CMAKE_BINARY_DIR})
LIST (FILTER CHECK_CXX_SOURCE_FILES EXCLUDE REGEX "${BUILDDIRECTORY}/*")
