SET (GIT_HASH "unknown")
FIND_PACKAGE (Git QUIET)
IF (GIT_FOUND)
  EXECUTE_PROCESS (
    COMMAND ${GIT_EXECTUABLE} log -1 --pretty-format:%h
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
ENDIF ()
# configure_file(${CMAKE_CURRENT_LIST_DIR}/version.hpp.
# ONLY_CMAKE_FIND_ROOT_PATH${TARGET_DIR}/version.hpp @ONLY)
