FILE (GLOB_RECURSE CMAKELISTS "CMakeLists.txt")
FILE (GLOB_RECURSE CMAKEMODULES "*.cmake")
LIST (APPEND CMAKEFORMATTINGFILES ${CMAKELISTS} ${CMAKEMODULES})

FOREACH (FILE ${CMAKEFORMATTINGFILES})
  EXECUTE_PROCESS (COMMAND cmake-format -i ${FILE} ${FILE})
ENDFOREACH (FILE)
