# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/max/Projects/testcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/max/Projects/testcpp/build

# Utility rule file for format.

# Include the progress variables for this target.
include CMakeFiles/format.dir/progress.make

CMakeFiles/format: main.cpp.stamp
CMakeFiles/format: probelibrary/benchmark/probe_benchmark.cpp.stamp
CMakeFiles/format: probelibrary/src/probe.cpp.stamp
CMakeFiles/format: probelibrary/tests/unit_test.cpp.stamp
CMakeFiles/format: test/test_gtest_based.cpp.stamp
CMakeFiles/format: test/test_main.cpp.stamp
CMakeFiles/format: probelibrary/include/probe.h.stamp
CMakeFiles/format: formatrules.txt


main.cpp.stamp: ../main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Formatting /home/max/Projects/testcpp/main.cpp and stamping it with /home/max/Projects/testcpp/build/main.cpp.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build
	/usr/bin/clang-format -i /home/max/Projects/testcpp/main.cpp
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/main.cpp.stamp

probelibrary/benchmark/probe_benchmark.cpp.stamp: ../probelibrary/benchmark/probe_benchmark.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Formatting /home/max/Projects/testcpp/probelibrary/benchmark/probe_benchmark.cpp and stamping it with /home/max/Projects/testcpp/build/probelibrary/benchmark/probe_benchmark.cpp.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build/probelibrary/benchmark
	/usr/bin/clang-format -i /home/max/Projects/testcpp/probelibrary/benchmark/probe_benchmark.cpp
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/probelibrary/benchmark/probe_benchmark.cpp.stamp

probelibrary/src/probe.cpp.stamp: ../probelibrary/src/probe.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Formatting /home/max/Projects/testcpp/probelibrary/src/probe.cpp and stamping it with /home/max/Projects/testcpp/build/probelibrary/src/probe.cpp.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build/probelibrary/src
	/usr/bin/clang-format -i /home/max/Projects/testcpp/probelibrary/src/probe.cpp
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/probelibrary/src/probe.cpp.stamp

probelibrary/tests/unit_test.cpp.stamp: ../probelibrary/tests/unit_test.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Formatting /home/max/Projects/testcpp/probelibrary/tests/unit_test.cpp and stamping it with /home/max/Projects/testcpp/build/probelibrary/tests/unit_test.cpp.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build/probelibrary/tests
	/usr/bin/clang-format -i /home/max/Projects/testcpp/probelibrary/tests/unit_test.cpp
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/probelibrary/tests/unit_test.cpp.stamp

test/test_gtest_based.cpp.stamp: ../test/test_gtest_based.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Formatting /home/max/Projects/testcpp/test/test_gtest_based.cpp and stamping it with /home/max/Projects/testcpp/build/test/test_gtest_based.cpp.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build/test
	/usr/bin/clang-format -i /home/max/Projects/testcpp/test/test_gtest_based.cpp
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/test/test_gtest_based.cpp.stamp

test/test_main.cpp.stamp: ../test/test_main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Formatting /home/max/Projects/testcpp/test/test_main.cpp and stamping it with /home/max/Projects/testcpp/build/test/test_main.cpp.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build/test
	/usr/bin/clang-format -i /home/max/Projects/testcpp/test/test_main.cpp
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/test/test_main.cpp.stamp

probelibrary/include/probe.h.stamp: ../probelibrary/include/probe.h
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Formatting /home/max/Projects/testcpp/probelibrary/include/probe.h and stamping it with /home/max/Projects/testcpp/build/probelibrary/include/probe.h.stamp"
	/usr/bin/cmake -E make_directory /home/max/Projects/testcpp/build/probelibrary/include
	/usr/bin/clang-format -i /home/max/Projects/testcpp/probelibrary/include/probe.h
	/usr/bin/cmake -E touch /home/max/Projects/testcpp/build/probelibrary/include/probe.h.stamp

build/formatrules.txt:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/max/Projects/testcpp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Generating build/formatrules.txt"
	cd /home/max/Projects/testcpp && echo generate\ rules----------
	cd /home/max/Projects/testcpp && python3 /home/max/Projects/testcpp/cmake_modules/scripts/generate_format_rules.py build >build/formatrules.txt

format: CMakeFiles/format
format: main.cpp.stamp
format: probelibrary/benchmark/probe_benchmark.cpp.stamp
format: probelibrary/src/probe.cpp.stamp
format: probelibrary/tests/unit_test.cpp.stamp
format: test/test_gtest_based.cpp.stamp
format: test/test_main.cpp.stamp
format: probelibrary/include/probe.h.stamp
format: build/formatrules.txt
format: CMakeFiles/format.dir/build.make

.PHONY : format

# Rule to build all files generated by this target.
CMakeFiles/format.dir/build: format

.PHONY : CMakeFiles/format.dir/build

CMakeFiles/format.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/format.dir/cmake_clean.cmake
.PHONY : CMakeFiles/format.dir/clean

CMakeFiles/format.dir/depend:
	cd /home/max/Projects/testcpp/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/max/Projects/testcpp /home/max/Projects/testcpp /home/max/Projects/testcpp/build /home/max/Projects/testcpp/build /home/max/Projects/testcpp/build/CMakeFiles/format.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/format.dir/depend

