name: Continuous Integration
run-name: ${{ github.actor }} submitting PR for ${{ github.head_ref }}
on: [push, pull_request]
jobs:
  build-devcontainer:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the devcontainer
        uses: devcontainers/ci@v0.3
        with: 
          imageName: ci-image
          runCmd: echo Success
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}:/workspace
          image: ci-image:latest
          run: /workspace/build.sh